version: "3.9"

services:
  apache:
    build:
      context: ./compose/twm-apache
    container_name: twm-apache
    ports:
      - "8080:8080"   # optional for debugging
    restart: unless-stopped

  nginx:
    build:
      context: ./compose/rproxy-nginx
    container_name: rproxy-nginx
    ports:
      - "8080:8080"
    depends_on:
      - apache
    restart: unless-stopped
