FROM docker.osgeo.org/geoserver:2.28.0

#USER root

# OpenShift arbitrary UID compatibility
#RUN chgrp -R 0 /usr/local/geoserver /usr/local/tomcat && \
#    chmod -R g=u /usr/local/geoserver /usr/local/tomcat

#USER 1001

EXPOSE 8080
