worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    access_log /dev/stdout;
    error_log  /dev/stderr;

    limit_req_zone $binary_remote_addr zone=twm_ratelimit:10m rate=25r/s;
	
	proxy_cache_path /tmp/nginx_cache levels=1:2 keys_zone=twm_cache:10m inactive=48h max_size=250m;
	
    server {
        listen 8080;

        server_name _;

        location / {
            limit_req zone=twm_ratelimit burst=10;
			
			proxy_pass http://twm-public-apache:8081;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
			
			proxy_cache twm_cache;
            proxy_cache_valid 200 48h;
			proxy_cache_valid 301 48h;
			proxy_cache_valid 404 1m;
            proxy_cache_use_stale error timeout updating;
			
            proxy_set_header If-Modified-Since $http_if_modified_since;
            proxy_set_header If-None-Match $http_if_none_match;
            add_header Cache-Control "public, must-revalidate" always;
        }
		
    }
}
